import type { CartLine } from '../types/commerce';
import { endpoint } from './api';

declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void }; } }
const loadScript = () => new Promise<void>((resolve, reject) => { if (window.Razorpay) return resolve(); const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = () => resolve(); script.onerror = () => reject(new Error('Unable to load Razorpay Checkout.')); document.head.appendChild(script); });
export async function payForCart(cart: CartLine[], onVerified: () => Promise<void>) {
  const [config, order] = await Promise.all([fetch(endpoint('/payments/config')).then(r => r.json()), fetch(endpoint('/payments/order'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ items: cart.map(line => ({ productId: line.id, quantity: line.quantity })) }) }).then(async r => { const body = await r.json(); if (!r.ok) throw new Error(body.error || 'Unable to start payment.'); return body; })]);
  if (!config.keyId) throw new Error('Razorpay test key is not configured.'); await loadScript();
  await new Promise<void>((resolve, reject) => new window.Razorpay!({ key: config.keyId, amount: order.amount, currency: order.currency, name: 'Nelture.ai', description: 'Grocery order', order_id: order.id, prefill: { name: order.customer.name, email: order.customer.email || '', contact: order.customer.contact || '' }, handler: async (payment: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) => { try { const verify = await fetch(endpoint('/payments/verify'), { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payment) }); const result = await verify.json(); if (!verify.ok || !result.verified) throw new Error(result.error || 'Payment verification failed.'); await onVerified(); resolve(); } catch (error) { reject(error); } }, modal: { ondismiss: () => reject(new Error('Payment was cancelled.')) } }).open());
}
